### ISSUE TITLE
AGI Failing @ SEND/RCV GOOGLE API Request/Response

### ISSUE THREAD

**Issue by geekinawe** [rgrokett/RaspiAsteriskGoogle#2]
Running clean install of Raspbian. Reviewed instructions multiple times.

Able to dial in and record question. I see the "in.wav" file created. I do not see the "out.wav" file created. In turn, this causes the 16K to 8K conversion to fail and the response doesn't playback.

When I manually run the "googlesamples-assistant-pushtotalk" command, I see the file go out to Google and the "out.wav" file is created with the response.

Debug enabled and core set debug 4 enabled in Asterisk.

Unable to determine why the "googlesamples" command is failing from AGI, but I believe this is where the failure is.

((Thank you for creating this, BTW - I have it hooked up to an antique phone right now!))

**Comment by rgrokett** [comment]
So I assume the ~/RaspiAsteriskGoogle/test.sh  ($ bash ./test.sh) script is working for you and you get no error messages and you get a good out.wav file from it?  (see page 9 in pdf doc)

Asterisk runs under a different userid from pi, so my guess is a linux permission or python environment issue.  All the python modules should be installed using sudo pip install so that they are system wide. _(note that the Google SDK docs talk about using python virtual env so as to not mess up any other python programs, but we don't care here since this is a "dedicated" proof of concept)_

Try running the test.sh program using "asterisk" userid:
```
$ sudo chsh -s /bin/bash asterisk     # Allows asterisk userid to access a shell
$ chmod 777 /home/pi/RaspiAsteriskGoogle   # Allow any id to write to this directory
$ sudo su - asterisk -c "cd /home/pi/RaspiAsteriskGoogle; bash ./test.sh"    # Run the test again as "asterisk" userid
```

After the bunch of DEBUG messages like previously, you should see:
...
DEBUG:root:ConverseResponse: audio_data (1600 bytes)
DEBUG:root:ConverseResponse: audio_data (594 bytes)
INFO:root:Finished playing assistant response.

AUDIO FILES:
-rw-r--r-- 1 pi       pi        55340 Apr 30 17:02 in.wav
-rw-r--r-- 1 asterisk asterisk 195838 Sep 29 20:40 out.wav

If you see a python error message from googlesamples-assistant-pushtotalk, try cut/pasting the error message into a google search browser window to see if you find a missing python package that needs to be installed system wide using $ sudo pip install XXXX

RASPBIAN STRETCH
Also note: I just tried to build this using the new Raspbian Stretch OS, but requires extra packages:

sudo python -m pip install grpcio
sudo python -m pip install --upgrade google-assistant-library
sudo python -m pip install --upgrade google-assistant-grpc
sudo python -m pip install --upgrade tenacity sounddevice

Once I had these, the bash ./test.sh worked and also the Asterisk 6666# ext worked.

OAUTH issue:
If you get an error with the "$ python -m google-oauthlib-tool --client-secrets..." cmd, leave off the leading **python -m**
Try:
$ google-oauthlib-tool --client-secrets \
/home/pi/client_secret.json \
--scope https://www.googleapis.com/auth/assistant-sdk-prototype \
--save --headless

**Comment by geekinawe** [comment]
After running back through your comments above, I was able to get "test.sh" to run successfully! The audio successfully made it to Google and back. I was able to validate the response by using aplay.

Unfortunately, I am still hitting a snag... When I run install.sh, I am able to successfully dial 6666# and record a question. A few moments later, I hear "Thank you," followed by a pause. After the pause, the script loops to the start again and I do not hear the response.

Upon entering "ls -l /tmp," I see the following two files have been created:
-rw-r--r-- 1 asterisk asterisk  86124 Nov 21 21:57 google_audio1201_in.wav
-rw-r--r-- 1 asterisk asterisk  43084 Nov 21 21:57 google_audio1201.wav

When I play the files, I hear my voice and my question.

Debugging in Asterisk shows:
[Nov 21 21:57:49] WARNING[1200][C-00000008]: file.c:774 ast_openstream_full: File /tmp/google_audio1201_8k does not exist in any format

I surmise that this error is created because the following command is not executing properly:
googlesamples-assistant-pushtotalk --credentials /home/pi/.config/google-oauthlib-tool/credentials.json -i /tmp/google_audio1201_in.wav -o /tmp/google_audio1201_out.wav -v

Hence, the "out.wav" files is not being created, so the rest of the script fails...

When I manually run the 'googlesamples' command from above, I do see the "out.wav" file created after the audio is send off to Google for processing.

Any suggestions at this point? Unfortunately, I do not see enough information coming back on the debug, so I am a bit stuck.

I am taking a fresh look at the initial Python commands again to see if I did something wrong... I do recall the Google documentation reffering to the virtual environment...

**Comment by rgrokett** [comment]
the python env is only needed if multiple python setups are needed. Since this raspi is dedicated to this project, it doesn’t matter.

**Comment by rgrokett** [comment]
Another thing is that the permissions to the /home/pi/.config/*.json file might not be set to allow the asterisk userid to read it. You can chmod 644 the path and json file to be sure it can be read by userids other than pi.

**Comment by ptruman** [comment]
I've got a similar issue :(
If I login as root and run the same commands the AGI calls, it works.
It I su to asterisk and run, it works.

If I run it from asterisk as an AGI call, it fails.

The recording of my speech works, but the response from Google seems to fail (if made at all)
The credentials.json file is stored within /home/asterisk/.config and the file and all folders are globally readable.

The log I get is:

<SIP/6002-00000075>AGI Rx << STREAM FILE /var/lib/asterisk/sounds/en/auth-thankyou "#"
<SIP/6002-00000075>AGI Tx >> 200 result=0 endpos=7679
<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: Converting /usr/bin/sox /tmp/google_audio21766.wav."
<SIP/6002-00000075>AGI Tx >> 200 result=0
<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: CMD: /usr/bin/sox /tmp/google_audio21766.wav -r 16000 /tmp/google_audio21766_in.wav"
<SIP/6002-00000075>AGI Tx >> 200 result=0
<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: Calling gRPC /usr/local/bin/googlesamples-assistant-pushtotalk"
<SIP/6002-00000075>AGI Tx >> 200 result=0
**<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: CMD: /usr/local/bin/ --credentials /home/asterisk/.config/google-oauthlib-tool/credentials.json -i /tmp/google_audio21766_in.wav -o /tmp/google_audio21766_out.wav -v"**
<SIP/6002-00000075>AGI Tx >> 200 result=0
<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: Got gRPC API response."
<SIP/6002-00000075>AGI Tx >> 200 result=0
<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: Converting 16K wav to 8K /tmp/google_audio21766.sln"
<SIP/6002-00000075>AGI Tx >> 200 result=0
<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: Playing /tmp/google_audio21766_8k"
<SIP/6002-00000075>AGI Tx >> 200 result=0
**<SIP/6002-00000075>AGI Rx << STREAM FILE /tmp/google_audio21766_8k "#"
[2019-07-10 16:24:22] WARNING[21757][C-00000052]: file.c:571 filehelper: File /tmp/google_audio21766_8k.sln detected to have zero size.**
<SIP/6002-00000075>AGI Tx >> 200 result=0 endpos=0
<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: Cleaning temp files."

The _out.wav is created (and owned by asterisk) but only has a RIFF WAVE header and nothing else.

I've moved the credentials.json to /tmp and updated the google.agi script to use that - and same error.
The /usr/local/bin/googlesamples-assistant-pushtotalk exe is globally executable.

Help please! :)

**Comment by rgrokett** [comment]
The 200 result=0 you see all show that the _in.wav was sent to Google and a good response returned, but the return data is zero length. This tells me that the credentials and permissions appear ok (I would expect an error if that were the issue.)  You can verify by looking in /var/log/asterisk/messages. 

Do the various audio files show wav data in them (not zero length)?

ls -l /tmp to see permissions and file sizes
-rw-rw----  1 asterisk asterisk 42924 Jul 11 19:21 google_audio22471.wav
-rw-rw----  1 asterisk asterisk 85804 Jul 11 19:21 google_audio22471_in.wav
-rw-rw----  1 asterisk asterisk 41836 Jul 11 19:21 google_audio22471_out.wav
-rw-rw----  1 asterisk asterisk 20896 Jul 11 19:21 google_audio22471_8k.sln

if _in.wav is zero, then the audio didn't get recorded. (I assume this is not the case)
If _out.wav is zero, then Google didn't hear the question. (play the _in.wav to hear what was sent.)
If _8k.sln is zero, then it may be a missing wav decoder in sox? 
Try:
sox -v  
Look for AUDIO FILE FORMATS:     ...  sln ... wav ...

aplay google_audio22471_in.wav   # "What time is it?"
aplay google_audio22471_out.wav   # "It's 7:31"
sox "google_audio22471_out.wav" -t raw -r 8k -s -2 -c 1 "google_audio22471_8k.sln"
aplay -f S16_LE google_audio22471_8k.sln    # "It's 7:31"


It might be that the path to googlesamples-assistant-pushtotalk isn't in the Asterisk AGI's environment, so might need the full path:
which googlesamples-assistant-pushtotalk
Add full path in the AGI:
my $command    = "/usr/local/bin/googlesamples-assistant-pushtotalk"

**Comment by ptruman** [comment]
Hi

Thanks for responding.
I'm flummoxed.

/var/log/asterisk/messages didn't exist, but I enabled it in FreePBX - and all I can see matches the logfile posted above, which is:


[2019-07-12 13:39:10] WARNING[24781][C-00000010] file.c: File /tmp/google_audio24861_8k.sln detected to have zero size.

The files I have are :

-rw-rw-rw-+ 1 asterisk asterisk     0 Jul 12 13:39 google_audio24861_8k.sln
-rw-rw-rw-+ 1 asterisk asterisk 77484 Jul 12 13:39 google_audio24861_in.wav
-rw-rw-rw-+ 1 asterisk asterisk    44 Jul 12 13:39 google_audio24861_out.wav
-rw-rw-rw-+ 1 asterisk asterisk 38764 Jul 12 13:39 google_audio24861.wav

So it's capturing the "ask a question" and converting that for sending to Google, but no response comes back.  The 44 byte file just has the RIFF WAVE header.

If I run "as root" or su to asterisk, it will work and all files populate, so the audio libs appear to be there, unless for some reason one is absent in a path (unlikely)

/tmp is writable (as it should be)

My google.agi config has full paths (now including the move of the json creds to /tmp) : 

my $command    = "/usr/local/bin/googlesamples-assistant-pushtotalk";
my $oauth_dir  = "/home/asterisk/.config/google-oauthlib-tool";
#my $api_json_file = "$oauth_dir/credentials.json";
my $api_json_file = "/tmp/credentials.json";

It's obviously *something* to do with the asterisk operating context, but I can't see what...

**Comment by rgrokett** [comment]
One thing I see is that in your first message log, it's missing the "googlesamples-assistant-pushtotalk" 
I assume that is a cut/paste error?  

<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: CMD: **/usr/local/bin/** --credentials /home/asterisk/.config/google-oauthlib-tool/credentials.json -i /tmp/google_audio21766_in.wav -o /tmp/google_audio21766_out.wav -v"

This is mine:
<SIP/5310-0000000a>AGI Rx << NOOP " -- google.agi: CMD: **/usr/local/bin/googlesamples-assistant-pushtotalk** --credentials /home/pi/.config/google-oauthlib-tool/credentials.json -i /tmp/google_audio27201_in.wav -o /tmp/google_audio27201_out.wav -v"

--------

From your last message, since you are able to run the pushtotalk command on the command-line and it works, then it appears that the only difference would be the environment variables that asterisk (Freepbx?) is running the AGI script under vs the bash command line.  I know FreePBX "locks down" its env by default for security.  

I assume this works on your command-line? (modify the wav file name as needed)
`googlesamples-assistant-pushtotalk --credentials /home/asterisk/.config/google-oauthlib-tool/credentials.json -i /tmp/google_audio21766_in.wav -o /tmp/google_audio21766_out.wav -v"`

You may need to add the following to your google.agi script:

`my $command    = "source /home/pi/.bashrc; googlesamples-assistant-pushtotalk";
`
This should import the .bashrc env variables into the shell that is executing the pushtotalk program. 

----

NOTE: Are you logging in as **pi** or as **asterisk**?   
(Normally, asterisk has no shell or password so cannot log in.) '
You need to source the .bashrc for the userid that you are logged in as. 
`whoami`

Note also that during installation the Python pip install commands must be executed with sudo otherwise they will install into local environment only and not globally. I assume this isn't the issue, since I would expect error messages in the logs. 

```
sudo python -m pip install --upgrade PySocks
sudo python -m pip install --upgrade google-auth-oauthlib[tool]
sudo python -m pip install --upgrade google-assistant-sdk

sudo python -m pip install grpcio
sudo python -m pip install --upgrade google-assistant-library
sudo python -m pip install --upgrade google-assistant-grpc
sudo python -m pip install --upgrade tenacity sounddevice
```
(From page 8 of the RaspiAsteriskGoogleInstallation.pdf doc)

**Comment by ptruman** [comment]
That's a good spot sir - but still something odd going on.

The only bit of google.agi I touched was the path to my json creds - so the $command line still reads:

`my $command    = "/usr/local/bin/googlesamples-assistant-pushtotalk";`

The file definitely exists:

`-rwxr-xr-x 1 root staff 241 Apr 18 15:33 /usr/local/bin/googlesamples-assistant-pushtotalk
`

The code section to call the command (direct cut & paste)

```
# SEND/RCV GOOGLE API Request/Response
console_log ("Calling gRPC $command") if ($debug);
my $v = "";
$v = "-v" if ($debug);
$cmd = "${command} --credentials ${api_json_file} -i ${tmpname}_in.wav -o ${tmp$
console_log ("CMD: $cmd") if ($debug);
$status = qx/$cmd/;
console_log ("Got gRPC API response.") if ($debug);

...and from my log :

<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: Calling gRPC **/usr/local/bin/googlesamples-assistant-pushtotalk**"
<SIP/6002-00000075>AGI Tx >> 200 result=0
<SIP/6002-00000075>AGI Rx << NOOP " -- google.agi: CMD: **/usr/local/bin/** --credentials /home/asterisk/.config/google-oauthlib-tool/credentials.json -i /tmp/google_audio21766_in.wav -o /tmp/google_audio21766_out.wav -v"

No idea why the second log line has lost the command name, but still included the path.
Also the -out file gets created, but it's zero bytes - so it's definitely called the pushtotalk :)

I'll try the environment thing.  I will add this isn't running on a pi, but my linux box - but I had it running before I rebuilt it - which is why I'm puzzled it's just not behaving "as is"....
