### ISSUE TITLE
Solution by using IAX

### ISSUE THREAD

**Issue by jstibenpb** [rgrokett/RaspiAsteriskGoogle#4]
Hi, is it possible to use IAX instead of SIP?

**Comment by rgrokett** [comment]
I assume you are wanting to set up an inbound IAX trunk so that a remote Asterisk PBX (or IAX provider) can be used to call the 6666# number.  The short answer is yes. But the long answer is if you know how to set up the IAX trunk and routing so that remote callers can dial the 6666 extension, you are in business. 
For details, google "iax trunk between asterisk servers" as a starting point.
